# Generated by Django 4.0.6 on 2022-08-01 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_leader_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='language',
            field=models.ManyToManyField(help_text='Select a language for this event', to='catalog.language'),
        ),
    ]
