# Generated by Django 4.0.6 on 2022-08-03 05:48

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_cohort_remove_event_leader_leader_events_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(default='nothing@sample.com', max_length=254),
        ),
        migrations.AddField(
            model_name='member',
            name='first_name',
            field=models.CharField(default='nothing', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='last_name',
            field=models.CharField(default='nothing', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='0000000000', help_text='Contact phone number', max_length=128, region=None),
        ),
    ]
