# Generated by Django 4.0.6 on 2022-08-03 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_member_email_member_first_name_member_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.RenameField(
            model_name='member',
            old_name='m_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='cohorts',
        ),
        migrations.AddField(
            model_name='cohort',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cohorts', to='catalog.member'),
        ),
        migrations.AddField(
            model_name='member',
            name='classes',
            field=models.ManyToManyField(related_name='member', through='catalog.Cohort', to='catalog.event'),
        ),
    ]
