# Generated by Django 4.0.6 on 2022-08-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_member_options_rename_m_id_member_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={},
        ),
        migrations.RemoveField(
            model_name='cohort',
            name='member',
        ),
        migrations.RemoveField(
            model_name='member',
            name='classes',
        ),
        migrations.AddField(
            model_name='member',
            name='cohorts',
            field=models.ManyToManyField(to='catalog.cohort'),
        ),
    ]
