# Generated by Django 4.0.6 on 2022-08-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_cohort_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohort',
            name='student',
        ),
        migrations.AddField(
            model_name='cohort',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Attending'), ('w', 'Waitlist')], default='m', help_text='Book availability', max_length=1),
        ),
    ]
