# Generated by Django 4.0.6 on 2022-08-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_event_is_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_lead',
            field=models.CharField(blank=True, choices=[('t', 'Teaching'), ('n', 'Not teaching')], default='t', max_length=1),
        ),
    ]
