# Generated by Django 4.0.6 on 2022-08-04 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0018_alter_event_is_lead'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leader',
            options={},
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_lead',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='email',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='last_name',
        ),
        migrations.AddField(
            model_name='eventinstance',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.leader'),
        ),
        migrations.AddField(
            model_name='leader',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='event',
            name='language',
        ),
        migrations.AddField(
            model_name='event',
            name='language',
            field=models.CharField(choices=[('all', 'ALL'), ('beginner', 'BEGINNER'), ('specialized', 'SPECIALIZED')], default='html', max_length=15),
        ),
        migrations.AlterField(
            model_name='event',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='event',
            name='level',
        ),
        migrations.AddField(
            model_name='event',
            name='level',
            field=models.CharField(choices=[('all', 'ALL'), ('beginner', 'BEGINNER'), ('specialized', 'SPECIALIZED')], default='all', max_length=15),
        ),
    ]
