# Generated by Django 4.0.6 on 2022-08-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_alter_leader_options_remove_event_is_lead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='language',
            field=models.CharField(choices=[('api', 'API'), ('css', 'CSS'), ('data', 'DATA'), ('html', 'HTML'), ('javascript', 'JAVASCRIPT')], default='html', max_length=15),
        ),
    ]
