# Generated by Django 4.0.6 on 2022-08-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_alter_event_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Teaching'), ('n', 'Not Teaching')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='eventinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Attending'), ('w', 'Waitlist'), ('n', 'Not Attending')], default='a', max_length=1),
        ),
    ]
