# Generated by Django 4.0.6 on 2022-08-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_event_status_alter_eventinstance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(blank=True, choices=[('t', 'Teaching'), ('n', 'Not Teaching')], default='t', max_length=1),
        ),
    ]
