# Generated by Django 4.0.6 on 2022-08-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_alter_event_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.AlterField(
            model_name='event',
            name='level',
            field=models.CharField(choices=[('all levels', 'ALL'), ('beginner', 'BEGINNER'), ('specialized', 'SPECIALIZED')], default='all', max_length=15),
        ),
    ]
